-- Detach public.users from Supabase auth.users
-- Drop legacy FK so Better-Auth can create independent users
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_constraint c
    JOIN pg_class t ON t.oid = c.conrelid
    JOIN pg_namespace n ON n.oid = t.relnamespace
    WHERE n.nspname = 'public' AND t.relname = 'users' AND c.conname = 'users_id_fkey'
  ) THEN
    ALTER TABLE "users" DROP CONSTRAINT "users_id_fkey";
  END IF;
END;
$$;

-- Ensure UUIDs are generated by DB for users.id
ALTER TABLE "users" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();

