import type { ChatModelCard } from '../types';

const togetheraiModels: ChatModelCard[] = [
  {
    id: 'meta-llama/Llama-3.3-70B-Instruct-Turbo',
    displayName: 'Llama 3.3 70B Instruct Turbo',
    description: 'Meta Llama 3.3多语言大模型，优化多语言对话。',
    type: 'chat',
    contextWindowTokens: 131_072,
    enabled: true,
    abilities: {
      functionCall: true,
    },
  },
  {
    id: 'meta-llama/Llama-3.2-3B-Instruct-Turbo',
    displayName: 'Llama 3.2 3B Instruct Turbo',
    description: 'Llama 3.2轻量模型，处理视觉和文本数据任务。',
    type: 'chat',
    contextWindowTokens: 131_072,
    enabled: true,
  },
  {
    id: 'meta-llama/Llama-Vision-Free',
    displayName: 'Llama 3.2 11B Vision Instruct (Free)',
    description: 'Llama 3.2视觉模型免费版，图像描述和问答表现出色。',
    type: 'chat',
    contextWindowTokens: 131_072,
    enabled: true,
    abilities: {
      vision: true,
    },
  },
  {
    id: 'meta-llama/Llama-3.2-90B-Vision-Instruct-Turbo',
    displayName: 'Llama 3.2 90B Vision Instruct Turbo',
    description: 'Llama 3.2大规模视觉模型，跨越视觉与语言推理。',
    type: 'chat',
    contextWindowTokens: 131_072,
    enabled: true,
    abilities: {
      vision: true,
    },
  },
  {
    id: 'meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo',
    displayName: 'Llama 3.1 8B Instruct Turbo',
    description: 'Llama 3.1 8B量化版，适合复杂任务处理。',
    type: 'chat',
    contextWindowTokens: 131_072,
    enabled: true,
    abilities: {
      functionCall: true,
    },
  },
  {
    id: 'meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo',
    displayName: 'Llama 3.1 70B Instruct Turbo',
    description: 'Llama 3.1 70B高效模型，适合高负载应用。',
    type: 'chat',
    contextWindowTokens: 131_072,
    enabled: true,
    abilities: {
      functionCall: true,
    },
  },
  {
    id: 'meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo',
    displayName: 'Llama 3.1 405B Instruct Turbo',
    description: 'Llama 3.1 405B超大规模模型，处理超大规模AI应用。',
    type: 'chat',
    contextWindowTokens: 130_815,
    enabled: true,
    abilities: {
      functionCall: true,
    },
  },
  {
    id: 'nvidia/Llama-3.1-Nemotron-70B-Instruct-HF',
    displayName: 'Llama 3.1 Nemotron 70B',
    description: 'NVIDIA定制大模型，对齐基准测试排名第一。',
    type: 'chat',
    contextWindowTokens: 32_768,
    enabled: true,
  },
  {
    id: 'deepseek-ai/DeepSeek-R1',
    displayName: 'DeepSeek R1',
    description: 'DeepSeek推理模型，强化学习优化，超越o1-mini。',
    type: 'chat',
    contextWindowTokens: 32_768,
    enabled: true,
    abilities: {
      reasoning: true,
    },
  },
  {
    id: 'deepseek-ai/DeepSeek-V3',
    displayName: 'DeepSeek V3',
    description: 'DeepSeek V3最新模型，性能对齐GPT-4o和Claude-3.5。',
    type: 'chat',
    contextWindowTokens: 16_384,
    enabled: true,
  },
  {
    id: 'Qwen/QwQ-32B-Preview',
    displayName: 'QwQ 32B Preview',
    description: 'Qwen实验性推理模型，专注增强AI推理能力。',
    type: 'chat',
    contextWindowTokens: 32_768,
    enabled: true,
    abilities: {
      reasoning: true,
    },
  },
  {
    id: 'Qwen/Qwen2.5-7B-Instruct-Turbo',
    displayName: 'Qwen 2.5 7B Instruct Turbo',
    description: 'Qwen2.5新版大模型，优化指令式任务处理。',
    type: 'chat',
    contextWindowTokens: 32_768,
    enabled: true,
  },
  {
    id: 'Qwen/Qwen2.5-72B-Instruct-Turbo',
    displayName: 'Qwen 2.5 72B Instruct Turbo',
    description: 'Qwen2.5 72B大规模模型，指令处理能力卓越。',
    type: 'chat',
    contextWindowTokens: 32_768,
    enabled: true,
  },
  {
    id: 'google/gemma-2-9b-it',
    displayName: 'Gemma 2 9B',
    description: 'Google Gemma 2 9B模型，高效指令响应。',
    type: 'chat',
    contextWindowTokens: 8192,
    enabled: true,
  },
  {
    id: 'google/gemma-2-27b-it',
    displayName: 'Gemma 2 27B',
    description: 'Google Gemma 2 27B通用模型，应用场景广泛。',
    type: 'chat',
    contextWindowTokens: 8192,
    enabled: true,
  },
  {
    id: 'mistralai/Mixtral-8x7B-Instruct-v0.1',
    displayName: 'Mixtral 8x7B Instruct',
    description: 'Mixtral MoE模型，适合大规模数据处理。',
    type: 'chat',
    contextWindowTokens: 32_768,
    enabled: true,
    abilities: {
      functionCall: true,
    },
  },
  {
    id: 'mistralai/Mixtral-8x22B-Instruct-v0.1',
    displayName: 'Mixtral 8x22B Instruct',
    description: 'Mixtral超级大模型，支持极高处理需求。',
    type: 'chat',
    contextWindowTokens: 65_536,
    enabled: true,
  },
];

export default togetheraiModels;
